name: rebuild

on:
  workflow_dispatch:
    inputs:
      CORRELATION_ID:
        description: 'Correlation Id for the rebuild workflow'
        required: true
      REPO:
        description: 'Repository to checkout'
        required: true
      COMMIT_SHA:
        description: 'Commit SHA to checkout to rebuild'
        required: true
      COMMAND:
        description: 'Build command to run'
        required: true
      GO_VERSION:
        description: 'Go version to use'
        required: true
      OUTPUT_FILE:
        description: 'Name of output binary file'
        required: true
      EXPECTED_CHECKSUM:
        description: 'Expected checksum of output binary file'
        required: true

permissions:  # added using https://github.com/nextlinux/secure-workflows
  contents: read

jobs:
  rebuild:
    name: rebuild-${{ github.event.inputs.CORRELATION_ID }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: nextlinux/harden-runner@v2.4.0 # v2.0.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.REPO }}
        ref: ${{ github.event.inputs.COMMIT_SHA }}
         
    
    - name: Set up Go 
      uses: actions/setup-go@v4.0.1 # v2.2.0
      with:
        go-version: ${{ github.event.inputs.GO_VERSION }}
        
    - run: ${{ github.event.inputs.COMMAND }}
    - run: | 
        sha=($(shasum -a256 ${{ github.event.inputs.OUTPUT_FILE }}))
        echo $sha
        if [[ "$sha" != "${{ github.event.inputs.EXPECTED_CHECKSUM }}" ]]
        then
          echo "Checksum not as expected"
          exit 1
        fi
